### ISSUE TITLE
bind-value无法实现输入框绑定

### ISSUE THREAD

**Issue by devtip** [ecomfe/san-website#36]
[表单输入框](https://ecomfe.github.io/san/tutorial/form/#输入框)一节中bind-value无法实现绑定，代码示例如下：

``` javascript
var MyApp = san.defineComponent({
    template: `
    <div>
        <input type="text" bind-value="name">
        <p>{{= name =}}</p>
    </div>`,

    initData: function () {
        return {
            name: 'San'
        }
    }
});

var myApp = new MyApp();
myApp.attach(document.body);
```

[但是看了下后面的内容，比如[select](https://ecomfe.github.io/san/tutorial/form/#select)一节， 你们想表达的意思似乎就是这种插值方法：

``` javascript
 <input type="text" value="{= name =}">
```

![image](https://user-images.githubusercontent.com/13482526/32401984-bedc7594-c155-11e7-91e5-0d8fedc0a4cd.png)

**Comment by LeuisKen** [comment]
已确认是文档更新遗漏的问题，马上处理。
